FROM golang:1.25.0-alpine AS builder

WORKDIR /app

ENV CGO_ENABLED=0

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM scratch

COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY migrations ./migrations

WORKDIR /migrations

ENTRYPOINT ["goose"]
