version: 3

vars:
  PROTO_DIR: proto
  OUT_DIR: ./gen/go

tasks:
  generate:
    dir: "{{.TASKFILE_DIR}}"
    aliases:
    - gen
    desc: Generate proto files
    cmds:
    - |
      echo "Generating Go code from proto files..."
      mkdir -p {{.OUT_DIR}}
      FILES=$(find {{.PROTO_DIR}} -name '*.proto')
      echo "Found proto files: ${FILES}"
      protoc -I {{.PROTO_DIR}} ${FILES} --go_out={{.OUT_DIR}} --go_opt=paths=source_relative --go-grpc_out={{.OUT_DIR}} --go-grpc_opt=paths=source_relative
  
  clear:
    dir: "{{.TASKFILE_DIR}}"
    aliases:
    - clr
    desc: Remove generated files
    cmds:
    - |
      echo "Cleanup generated files"
      rm -rf {{.OUT_DIR}}
