{
 "title": "PostgreSQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Is Running",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pg_up == 1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname!~\"template0|template1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read/Write per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname!~\"template0|template1\"}[1m]) * 8192",
     "legendFormat": "{{datname}}_ read"
    },
    {
     "expr": "rate(pg_stat_database_blks_written{datname!~\"template0|template1\"}[1m]) * 8192",
     "legendFormat": "{{datname}}_ write"
    }
   ]
  },
  {
   "title": "Select per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_scan{datname!~\"template0|template1\", relname!~\"goose_db_version\"}[1m])",
     "legendFormat": "{{relname}}_seq"
    },
    {
     "expr": "rate(pg_stat_user_tables_idx_scan{datname!~\"template0|template1\", relname!~\"goose_db_version\"}[1m])",
     "legendFormat": "{{relname}}_idx"
    }
   ]
  },
  {
   "title": "Insert per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{datname!~\"template0|template1\", relname!~\"goose_db_version\"}[1m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Update per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{datname!~\"template0|template1\", relname!~\"goose_db_version\"}[1m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Delete per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{datname!~\"template0|template1\", relname!~\"goose_db_version\"}[1m])",
     "legendFormat": "{{relname}}"
    }
   ]
  }
 ]
}