name: Build App
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Print all git tags
      run: |
        echo "All tags:"
        git tag
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/auth
        tags: |
          type=edge
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Print generated tags
      run: |
        echo "All tags: ${{ steps.meta.outputs.tags }}"
        echo "All labels: ${{ steps.meta.outputs.labels }}"
    - name: Install Task
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
        sudo mv ./bin/task /usr/local/bin/task
        task --version
    - name: Build Auth
      run: |
        task build_auth
    - name: Pull Dep Images
      run: |
        docker pull postgres:17.5
    - name: Run Tests
      run: |
        task test_auth
    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag & Push
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: |
        for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' ' '); do
          echo "Tagging image as: $tag"
          docker tag auth:latest "$tag"
          docker push "$tag"
        done
