name: Build App
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Print all git tags
      run: |
        echo "All tags:"
        git tag
    - name: Docker meta (Auth)
      id: meta_auth
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/got-auth
        tags: |
          type=edge
          type=semver,pattern={{version}}
    - name: Docker meta (Gateway)
      id: meta_gateway
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/got-gateway
        tags: |
          type=edge
          type=semver,pattern={{version}}
    - name: Docker meta (Auth)
      id: meta_migrator
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/got-migrator
        tags: |
          type=edge
          type=semver,pattern={{version}}
    - name: Install Task
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
        sudo mv ./bin/task /usr/local/bin/task
        task --version
    - name: Build Services
      run: |
        task build
    - name: Pull Dep Images
      run: |
        docker pull postgres:17.5
    - name: Run Tests
      run: |
        task test_auth
    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag & Push
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Tag & Push Auth"
        for tag in $(echo "${{ steps.meta_auth.outputs.tags }}" | tr ',' ' '); do
          echo "Tagging images as: $tag"
          docker tag got-auth:latest "$tag"
          docker push "$tag"
        done
        echo "Tag & Push Gateway"
        for tag in $(echo "${{ steps.meta_gateway.outputs.tags }}" | tr ',' ' '); do
          echo "Tagging images as: $tag"
          docker tag got-gateway:latest "$tag"
          docker push "$tag"
        done
        echo "Tag & Push Migrator"
        for tag in $(echo "${{ steps.meta_migrator.outputs.tags }}" | tr ',' ' '); do
          echo "Tagging images as: $tag"
          docker tag got-migrator:latest "$tag"
          docker push "$tag"
        done
